export const data = [
  {
    name: 'Cam thảo Hoàng Long',
    description: 'Cam thảo nhập từ công ty Hoàng Long',
    id: 10110,
    quantity: 156,
    unit: 'Kilogram',
    category: 'Thảo dược',
    supplier: 'Hoàng Linh',
    status: ['Disabled'],
  },
  {
    name: 'Cam thảo Hoàng Long',
    description: 'Cam thảo nhập từ công ty Hoàng Long',
    id: 10110,
    quantity: 156,
    unit: 'Kilogram',
    category: 'Thảo dược',
    supplier: 'Hoàng Linh',
    status: ['Disabled'],
  },
  {
    name: 'Cam thảo Hoàng Long',
    description: 'Cam thảo nhập từ công ty Hoàng Long',
    id: 10110,
    quantity: 156,
    unit: 'Kilogram',
    category: 'Thảo dược',
    supplier: 'Hoàng Linh',
    status: ['Disabled'],
  },
]
